export const countryOptions = [
  'Albania', 'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic',
  'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary',
  'Iceland', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta',
  'Moldova', 'Montenegro', 'North Macedonia',
  'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Serbia',
  'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey',
  'Ukraine', 'United Kingdom'
];

export const countryCallingCodes: Record<string, string> = {
  Albania: '355',
  Australia: '61',
  Austria: '43',
  Belgium: '32',
  'Bosnia and Herzegovina': '387',
  Brazil: '55',
  Bulgaria: '359',
  Canada: '1',
  China: '86',
  Croatia: '385',
  Cyprus: '357',
  'Czech Republic': '420',
  Denmark: '45',
  Estonia: '372',
  Finland: '358',
  France: '33',
  Germany: '49',
  Greece: '30',
  Hungary: '36',
  Iceland: '354',
  India: '91',
  Ireland: '353',
  Italy: '39',
  Japan: '81',
  Latvia: '371',
  Lithuania: '370',
  Luxembourg: '352',
  Malta: '356',
  Mexico: '52',
  Moldova: '373',
  Montenegro: '382',
  Netherlands: '31',
  'North Macedonia': '389',
  Norway: '47',
  Poland: '48',
  Portugal: '351',
  Romania: '40',
  Serbia: '381',
  Singapore: '65',
  Slovakia: '421',
  Slovenia: '386',
  'South Korea': '82',
  Spain: '34',
  Sweden: '46',
  Switzerland: '41',
  Turkey: '90',
  Ukraine: '380',
  'United Arab Emirates': '971',
  'United Kingdom': '44',
  'United States': '1'
};

export const phoneCountryOptions = Object.keys(countryCallingCodes).sort((a, b) => a.localeCompare(b));

export const cityOptions: Record<string, string[]> = {
  Albania: ['Tirana', 'Durres', 'Vlore', 'Other'],
  'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Mostar', 'Other'],
  Austria: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Other'],
  Belgium: ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liege', 'Other'],
  Bulgaria: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Other'],
  Croatia: ['Zagreb', 'Split', 'Rijeka', 'Dubrovnik', 'Other'],
  Cyprus: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Other'],
  'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Other'],
  Denmark: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Other'],
  Estonia: ['Tallinn', 'Tartu', 'Parnu', 'Other'],
  Finland: ['Helsinki', 'Espoo', 'Tampere', 'Turku', 'Other'],
  France: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Bordeaux', 'Lille', 'Other'],
  Germany: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Dusseldorf', 'Stuttgart', 'Other'],
  Greece: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Other'],
  Hungary: ['Budapest', 'Debrecen', 'Szeged', 'Pecs', 'Other'],
  Iceland: ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Other'],
  Ireland: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Other'],
  Italy: ['Milan', 'Prato', 'Rome', 'Florence', 'Turin', 'Bologna', 'Naples', 'Venice', 'Other'],
  Latvia: ['Riga', 'Daugavpils', 'Liepaja', 'Other'],
  Lithuania: ['Vilnius', 'Kaunas', 'Klaipeda', 'Other'],
  Luxembourg: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Other'],
  Malta: ['Valletta', 'Birkirkara', 'Mosta', 'Sliema', 'Other'],
  Moldova: ['Chisinau', 'Balti', 'Tiraspol', 'Other'],
  Montenegro: ['Podgorica', 'Budva', 'Kotor', 'Other'],
  Netherlands: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Other'],
  'North Macedonia': ['Skopje', 'Bitola', 'Ohrid', 'Other'],
  Norway: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Other'],
  Poland: ['Warsaw', 'Krakow', 'Wroclaw', 'Poznan', 'Gdansk', 'Lodz', 'Other'],
  Portugal: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro', 'Other'],
  Romania: ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi', 'Constanta', 'Other'],
  Serbia: ['Belgrade', 'Novi Sad', 'Nis', 'Other'],
  Slovakia: ['Bratislava', 'Kosice', 'Presov', 'Other'],
  Slovenia: ['Ljubljana', 'Maribor', 'Koper', 'Other'],
  Spain: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Malaga', 'Bilbao', 'Alicante', 'Other'],
  Sweden: ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala', 'Other'],
  Switzerland: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Lugano', 'Other'],
  Turkey: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Other'],
  Ukraine: ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv', 'Dnipro', 'Other'],
  'United Kingdom': ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Glasgow', 'Edinburgh', 'Other']
};

export const getCityOptions = (country: string) => {
  const cities = cityOptions[country] || [];
  return cities.includes('Other') ? cities : [...cities, 'Other'];
};
